# Generated by Django 3.1.2 on 2020-10-21 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0002_auto_20201019_1252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='cancled_at',
            new_name='cancelled_at',
        ),
    ]
